### ISSUE TITLE
scope of project

### ISSUE THREAD

**Issue by ds-04** [gabrieleiannetti/lfs-utils#1]
Hi,

Not an issue. Interested to know the scope of the project.

I'm considering wrapping _lfs quota_ with python to manage auto-expiry of quotas and enforcement of. Would such a thing be applicable within this?

thanks

**Comment by gabrieleiannetti** [comment]
Hi,  
sorry, totally forgot to activate the discussions section in this project.  
That would be better fit in there.  

Okay, anyways...  

# Scope of the Project

Since we are partly using Python for our Lustre tool chain, I thought it would be a good idea to provide one code base for common Lustre utility tasks, so that it can be used in different projects and also eliminate duplicate code.

I first started migrating this library into the [cyclone](https://github.com/GSI-HPC/cyclone-distributed-task-driven-framework) project for Lustre specific code sections.

#  Wrapping lfs quota

Hmm, sounds interesting!  

Well, we are always open for new ideas and maybe we all could benefit from this.  

Generally yes, please consider opening a discussion about new ideas or in this case you could also create an issue for `lfs quota management  auto-expiry and enforcement` to give us a more precise picture about the idea and how it should work...  

You welcome!

Best
Gabriele

**Comment by ds-04** [comment]
Hi Gabriele

OK thanks for clarifying.

``lfs quota management auto-expiry and enforcement`` I have some code I've worked on. I. Perhaps we can both work on it, if that is of interest to you.

I will close this issue and open a discussion at some point.

David
